name: CI

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: GGJ25-kh-teamC

jobs:
  export:
    strategy:
      matrix:
        export: 
          - { platform: windows, ext: exe }
          - { platform: linux, ext: x86_64 }
          - { platform: mac, ext: zip }
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    env:
      PLATFORM: ${{ matrix.export.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/$PLATFORM
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose \
            --export-release "$PLATFORM" \
            "$EXPORT_DIR/$PLATFORM/$EXPORT_NAME.${{ matrix.export.ext }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM }}
          path: build/${{ env.PLATFORM }}
