name: CI

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: GGJ25-kh-teamC

jobs:
  export:
    strategy:
      matrix:
        platform: [windows, linux, mac]
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "${{ matrix.platform }}" "$EXPORT_DIR/${{ matrix.platform }}/$EXPORT_NAME"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
